### PR TITLE
Fixed filament counting when print cancelled

### PR DESCRIPTION
**Pull request by doug-a-brunner**
I found if I cancelled a print, the filament consumed would not be subtracted from the spool's contents. OctoPrint 1.3.4 does not properly generate the PRINT_CANCELLED event (which would have made this fix a one-liner), so I refactored the code to use the state change event instead.

### CODE REVIEW

**Comment by malnvenshorn** [comment]
This issue is new to me. Because the PRINT_FAILED event is fired along with the PRINT_CANCELLED event this case is covered. Have you ensured that it is not a frontend issue? I observed that sometimes the frontend gets notified before the backend updates the filament therefore the stats aren't updated in the UI, but haven't found a solution yet.

**Comment by doug-a-brunner** [comment]
I would have expected that, but I found that actually as of OctoPrint 1.3.4 neither PRINT_FAILED nor PRINT_CANCELLED fires when I cancel a print. I verified this by adding a log output to on_event; when I started and cancelled a print the event stream looked like this:

  `PrinterStateChanged` (to `PRINTING`)
  `PrintStarted`
  `Home`
  `Home`
  Lots of `ZChange` as the print runs
  `PrinterStateChanged` (to `OPERATIONAL`)
  `ZChange` (I manually moved the print bed clear of the nozzle)
  `Shutdown` (shutting down the server to remove the log output)

I agree this is an API violation by OctoPrint, but it looks from the [documentation](http://docs.octoprint.org/en/master/events/index.html#printing) like the print state transition events are being deprecated, so perhaps maintaining them is not a priority anymore?

**Comment by malnvenshorn** [comment]
Some properties of the payload are deprecated not the events. What is the content of the event variable when you cancel a print? The on_event function must be triggered somehow, otherwise your solution won't work either. Does the issue persists in OctoPrint 1.3.5?

**Comment by malnvenshorn** [comment]
Did some digging. The cause of this issue is that your printer firmware is not answering die M114 command which is send on pausing/stopping a job, if it is not disabled in settings.

**Comment by doug-a-brunner** [comment]
The only event I get on cancelling the print is `PrinterStateChanged`, with `payload['state_id'] == 'OPERATIONAL'`. I haven't tried 1.3.5, I'll load it up when I get a chance.

Interesting about the `M114` issue...I looked at the traffic when I cancelled a print, and it appears that my printer's firmware (Redeem) may be answering the commands in the wrong order (and possibly sending too many `ok`s), creating the problem. Here's a snippet from the terminal:
  `Send: N511 G1 X-31.269 Y13.604 E0.0004*113`
  `Recv: ok`
  `Send: N512 G1 X-31.281 Y13.576 E0.0006*112`
  `Recv: ok`
  `Send: N513 G1 X-31.289 Y13.557 E0.0004*120`
  `Changing monitoring state from 'Printing' to 'Operational'`
  `Send: M400`
  `Send: M114`
  `Recv: ok C: A:0.0 mm B:0.0 mm C:0.0 mm E:5.6 mm H:0.0 mm X:-31.3 mm Y:13.6 mm Z:0.1 mm`
  `Recv: ok`
  `Recv: ok`
  `Recv: ok`
  `Recv: ok`
  `Send: M105`
  `Recv: ok T:226.9/230.0 T1:0.0/0.0 T0:226.9/230.0 B:120.1/120.0 @:162.0`
  `Send: M105`
  `Recv: ok T:227.6/230.0 T1:0.0/0.0 T0:227.6/230.0 B:120.1/120.0 @:150.0`

Thanks for researching this. I couldn't find the setting to disable sending `M114` - do you know where to look for it?

**Comment by malnvenshorn** [comment]
I'm reopening this pull request, because I'm not ruling out this merge. It could help to fix #18, but have to play around a bit more.

**Pull request merged**
