### PR TITLE
[WIP] Debug for printer with shared nozzle/hotend

### PR DESCRIPTION
**Pull request by gillg**
Debug JS when try to setup tool temp offset on printer with shared nozzle

### CODE REVIEW

**Comment by malnvenshorn** [comment]
Are you going to submit a mergeable pull request in the near future? I would like to integrate this fix in the next release :-)

**Comment by gillg** [comment]
Hi ! Yes I will do it but I have no computer actually ^^ I hope, I could make the request on monday.

**Comment by gillg** [comment]
Normaly it's already ok, but I not tested it

**Comment by malnvenshorn** [comment]
The issue is that you are ~70 commits behind with your branch and a lot has changed. The temperature offset will now be set in `octoprint_filamentmanager/__init__.py`

**Comment by malnvenshorn** [comment]
Just tested again and the issue seems already be fixed by c63f4803999b74e6b70cdfaeb473cde6b7254497

**Comment by gillg** [comment]
Yes you are true. Try catch is less elegant because it not fix the real problem in this case, but the bug should not appear :)

**Comment by malnvenshorn** [comment]
There is no exception thrown. OctoPrint handles this case quite well ;-)

**Pull request closed without merging**
