### PR TITLE
Added missing var declaration.

### PR DESCRIPTION
**Pull request by astateofblank**
I was also experiencing the issue reported in #16. I noticed the error in the console while using Chrome Version 61.0.3163.100 (Official Build) (64-bit). Patching this locally fixed the issue for me.

### CODE REVIEW

**Comment by malnvenshorn** [comment]
Thanks. I totally missed that one. But I highly doubt that this is the cause of the issue. The missing _var_ statement means that this is not a local variable.

**Comment by astateofblank** [comment]
You're right! I just assumed 'use strict' had been declared in filamentmanager.js. OctoPrint bundles all of the plugin's JavaScript together by defalut though, and it doesn't do anything to isolate their scopes. In my case, the "OctoPrint Anywhere" plugin is declaring 'use strict'; in the global scope. 

I would guess that is why its been hard to replicate - any number of plugins could be declaring 'use strict'; in the global scope.

Thanks for all of the hard work on Filament Manager.

**Comment by malnvenshorn** [comment]
This explains why you got a javascript error and it could be related to the issue after all. But I think it is a bad choice from the author of the "OctoPrint Anywhere" plugin to put this declaration in global scope because it can easily break other plugins.

**Comment by astateofblank** [comment]
I partially agree, but first and foremost I appreciate you merging the fix. You will have to be aware of the complication that your code may have to be strict compliant. In my mind, the responsibility is on OctoPrint to progress the ecosystem:

https://github.com/foosel/OctoPrint/issues/2200

OctoPrint Anywhere should want to improve the ecosystem as well though:

https://github.com/kennethjiang/OctoPrint-Anywhere/issues/28

OctoPrint Anywhere doesn't require jQuery, so the `$` domReady template isn't really useful. Again, OctoPrint can address this systematically, so I'd appreciate any support or feedback you can give as a plugin developer to that issue.

**Comment by malnvenshorn** [comment]
Of course it was never my intention to use a global variable. And you are absolutely right. The best solution is if OctoPrint would take care of putting each plugin into their own scope. But for now I've added _"use strict";_ to my scripts.

**Pull request merged**
